### ISSUE TITLE
Adventure dropdown for entry create is slow

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#271] opened 2022-01-11 23:06 UTC
## Description

When accessing a form that requires an adventure text field, the text field is a dropdown that have all adventures as options which makes the dropdown options load very slowly.

## Expected Behavior

For good UX, the dropdown should be fast.

## Actual Behavior

The dropdown appears slowly.

## Steps to Reproduce

1. Go to character page, click DM ENTRY, click CREATE
2. Click on adventure dropdown
3. Wait...

## Context

Accessing the adventure dropdown is painful. We want it to be fast.

## Possible Fix

Debounce when typing and after debounce, make a request to refresh props for the search.

# Other

**Comment by m-triassi** [comment] 2022-01-12 00:01
Ah whoops duplicate of #219 ! Closing

**Closed by m-triassi** 2022-01-12 00:01 UTC
Labels: bug, front end
